platform :ios, '12.0'

use_frameworks!

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FinikIosSdk_Example' do
  
  install_all_flutter_pods(flutter_application_path)

  pod 'FinikIosSdk', :path => '../'

  target 'FinikIosSdk_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
