platform :ios, '12.0'

target 'FinikIosSdk_Example' do
  use_frameworks!

  pod 'FinikIosSdk', :path => '../'

  target 'FinikIosSdk_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
